#
# qStrGatherHrPositionRdf.rq
# updated 140623 - changed newhr > hr
# queries HRIS for all details related to a position
# TODO:  fix this to pull only HR Graph rdf and adjust output
# TODO: this needs to exclude explicit links to organization.  We do that bit elsewhere.
# DONE: commented links to non essential RDF
# made primaryUnitCode optional 130303

PREFIX hr: <http://vivo.cornell.edu/ns/hr/0.9/hr.owl#>  
PREFIX cuvivo: <http://vivo.cornell.edu/individual/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX titlemap: <http://vivo.library.cornell.edu/ns/hr/titleMapping#> 

CONSTRUCT {
      ?job hr:company ?hrpPosnCompany .
      ?job hr:dLevelCode ?hrpDLevelCode .
      ?job hr:dLevelOrgName ?hrpDLevelOrgName .
      ?job hr:jobFamily ?hrpJobFamily .
      ?job hr:jobFamilyGroup ?hrpJobFamilyGroup .
      ?job hr:supOrgCode ?hrpSupOrgCode .
      ?job vivo:relates ?hrpPosnInOrganization .
      ?hrpPosnInOrganization vivo:relatedBy ?job  .
      ?job rdfs:label ?jobLabel .
      ?job hr:primaryJob ?hrjPrimaryJob .
      ?job vivo:hrJobTitle ?hrjHrJobTitle .
      ?hrjJobForPerson vivo:relatedBy ?job .
      ?job vivo:relates ?hrjJobForPerson .
}
WHERE
{
  # querying HRIS endpoint
  # get Workday->D2R format rdf, then write it as vivo 1.6 format rdf.
  SERVICE <http://vivo-migrate.library.cornell.edu/d2r>
    {
      #then, list all job-specific RDF
      VARVALUE rdfs:label ?jobLabel .
      VARVALUE hr:jobId ?hrjJobId .
      VARVALUE hr:jobInPosition ?position .
      VARVALUE hr:primaryJob ?hrjPrimaryJob .
      VARVALUE hr:startDate ?hrjStartDate .
      VARVALUE vivo:hrJobTitle ?hrjHrJobTitle .
      VARVALUE vivo:jobForPerson ?hrjJobForPerson .
     
      # list all position-specific RDF
      ?position hr:company ?hrpPosnCompany .
      ?position hr:dLevelCode ?hrpDLevelCode .
      ?position hr:dLevelOrgName ?hrpDLevelOrgName .
      ?position hr:jobCode ?hrpJobCode .
      ?position hr:jobFamily ?hrpJobFamily .
      ?position hr:jobFamilyGroup ?hrpJobFamilyGroup .
      ?position hr:kfsOrgCode ?hrpKfsOrgCode .
      ?position hr:positionForJob ?job .
      ?position hr:supOrgCode ?hrpSupOrgCode .
      ?position vivo:positionInOrganization ?hrpPosnInOrganization .
     } 
}