#

# qStrGetHrJobAndOrgForHrPerson.rq
# updated 140715 - v1.6
# This query takes a position URI varvalue and returns 
# position and org pairs


PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX hr: <http://vivo.cornell.edu/ns/hr/0.9/hr.owl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vivoc: <http://vivo.library.cornell.edu/ns/0.1#>

vivoc:
CONSTRUCT 
  {
  #?job vivo:positionInOrganization ?org .
  #?org vivo:organizationForPosition ?job .
  ?job vivo:relates ?vivoorg .
  ?vivoorg vivo:relatedBy ?job .
   }

WHERE
{
  # querying HRIS endpoint
  SERVICE <HRISSERV>
    {
    # not coming in as person local name
    # for whatever reason, we see qStrGetPosnOrgForOneHrisPerson
    VARVALUE hr:personInJob ?job .
    ?job hr:jobInPosition ?position .
    ?position vivo:positionInOrganization ?org .
    #?org a foaf:Organization .
    ?org hr:deptCode ?deptCode .
    }
  # querying VIVO endpoint
  SERVICE <VIVOSERV>
    {
       ?vivoorg vivoc:departmentHRcode ?deptCode .   
    }  
}